import type { NextPage } from 'next'
import Head from 'next/head'
import DefaultLayout from '../components/layouts/DefaultLayout'
import NavigationBar from '../components/modules/navigation/NavigationBar'
import Welcome from '../components/modules/Welcome'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DefaultLayout>
        <div className="h-screen">
          <NavigationBar name={"Xenta Web"} />
          <Welcome />
        </div>
      </DefaultLayout>
    </div>
  )
}

export default Home
